package parser

// Code generated by /home/unok/.cache/go-build/9f/9fb58ad683aaa01a9da9c138fa4306a4503d614221681e98aaf5d11de2423a6a-d/peg internal/parser/parser.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleroot
	ruleEOT
	ruleexpression
	ruletitle_info
	ruletable_info
	rulecomment
	ruleempty_line
	ruletable_name_info
	rulecolumn_info
	rulecolumn_attribute
	rulerelation
	rulecolumn_comment
	ruleindex_info
	rulegroups_decl
	rulegroup_string
	ruletitle
	rulecomment_string
	rulewhitespace
	rulenewline
	rulespace
	rulenotnull
	ruleunique
	ruleerd
	rulereal_table_name
	ruletable_name
	rulereal_column_name
	rulecolumn_name
	rulerelation_point
	rulepkey
	rulecol_type
	ruledefault
	rulecardinality_right
	rulecardinality_left
	rulecardinality
	rulePegText
	ruleAction0
	ruleAction1
	ruleAction2
	ruleAction3
	ruleAction4
	ruleAction5
	ruleAction6
	ruleAction7
	ruleAction8
	ruleAction9
	ruleAction10
	ruleAction11
	ruleAction12
	ruleAction13
	ruleAction14
	ruleAction15
	ruleAction16
	ruleAction17
	ruleAction18
	ruleAction19
	ruleAction20
	ruleAction21
	ruleAction22
	ruleAction23
)

var rul3s = [...]string{
	"Unknown",
	"root",
	"EOT",
	"expression",
	"title_info",
	"table_info",
	"comment",
	"empty_line",
	"table_name_info",
	"column_info",
	"column_attribute",
	"relation",
	"column_comment",
	"index_info",
	"groups_decl",
	"group_string",
	"title",
	"comment_string",
	"whitespace",
	"newline",
	"space",
	"notnull",
	"unique",
	"erd",
	"real_table_name",
	"table_name",
	"real_column_name",
	"column_name",
	"relation_point",
	"pkey",
	"col_type",
	"default",
	"cardinality_right",
	"cardinality_left",
	"cardinality",
	"PegText",
	"Action0",
	"Action1",
	"Action2",
	"Action3",
	"Action4",
	"Action5",
	"Action6",
	"Action7",
	"Action8",
	"Action9",
	"Action10",
	"Action11",
	"Action12",
	"Action13",
	"Action14",
	"Action15",
	"Action16",
	"Action17",
	"Action18",
	"Action19",
	"Action20",
	"Action21",
	"Action22",
	"Action23",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type Parser struct {
	parserBuilder

	Buffer string
	buffer []rune
	rules  [60]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *Parser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *Parser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *Parser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *Parser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *Parser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *Parser) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func (p *Parser) Execute() {
	buffer, _buffer, text, begin, end := p.Buffer, p.buffer, "", 0, 0
	for _, token := range p.Tokens() {
		switch token.pegRule {

		case rulePegText:
			begin, end = int(token.begin), int(token.end)
			text = string(_buffer[begin:end])

		case ruleAction0:
			p.Err(begin, buffer)
		case ruleAction1:
			p.Err(begin, buffer)
		case ruleAction2:
			p.setTitle(text)
		case ruleAction3:
			p.addTableTitleReal(text)
		case ruleAction4:
			p.addTableTitle(text)
		case ruleAction5:
			p.addPrimaryKey(text)
		case ruleAction6:
			p.setColumnNameReal(text)
		case ruleAction7:
			p.setColumnName(text)
		case ruleAction8:
			p.addColumnType(text)
		case ruleAction9:
			p.setNotNull()
		case ruleAction10:
			p.setUnique()
		case ruleAction11:
			p.setColumnDefault(text)
		case ruleAction12:
			p.setWithoutErd()
		case ruleAction13:
			p.setRelationSource(text)
		case ruleAction14:
			p.setRelationDestination(text)
		case ruleAction15:
			p.setRelationTableNameReal(text)
		case ruleAction16:
			p.addComment(text)
		case ruleAction17:
			p.setIndexName(text)
		case ruleAction18:
			p.setIndexColumn(text)
		case ruleAction19:
			p.setIndexColumn(text)
		case ruleAction20:
			p.setUniqueIndex()
		case ruleAction21:
			p.addGroup(text)
		case ruleAction22:
			p.addGroup(text)
		case ruleAction23:
			p.markGroupsDecl()

		}
	}
	_, _, _, _, _ = buffer, _buffer, text, begin, end
}

func Pretty(pretty bool) func(*Parser) error {
	return func(p *Parser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*Parser) error {
	return func(p *Parser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *Parser) Init(options ...func(*Parser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 root <- <((expression EOT) / (expression <.+> Action0 EOT) / (<.+> Action1 EOT))> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				{
					position2, tokenIndex2 := position, tokenIndex
					if !_rules[ruleexpression]() {
						goto l3
					}
					if !_rules[ruleEOT]() {
						goto l3
					}
					goto l2
				l3:
					position, tokenIndex = position2, tokenIndex2
					if !_rules[ruleexpression]() {
						goto l4
					}
					{
						position5 := position
						if !matchDot() {
							goto l4
						}
					l6:
						{
							position7, tokenIndex7 := position, tokenIndex
							if !matchDot() {
								goto l7
							}
							goto l6
						l7:
							position, tokenIndex = position7, tokenIndex7
						}
						add(rulePegText, position5)
					}
					if !_rules[ruleAction0]() {
						goto l4
					}
					if !_rules[ruleEOT]() {
						goto l4
					}
					goto l2
				l4:
					position, tokenIndex = position2, tokenIndex2
					{
						position8 := position
						if !matchDot() {
							goto l0
						}
					l9:
						{
							position10, tokenIndex10 := position, tokenIndex
							if !matchDot() {
								goto l10
							}
							goto l9
						l10:
							position, tokenIndex = position10, tokenIndex10
						}
						add(rulePegText, position8)
					}
					if !_rules[ruleAction1]() {
						goto l0
					}
					if !_rules[ruleEOT]() {
						goto l0
					}
				}
			l2:
				add(ruleroot, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 EOT <- <!.> */
		func() bool {
			position11, tokenIndex11 := position, tokenIndex
			{
				position12 := position
				{
					position13, tokenIndex13 := position, tokenIndex
					if !matchDot() {
						goto l13
					}
					goto l11
				l13:
					position, tokenIndex = position13, tokenIndex13
				}
				add(ruleEOT, position12)
			}
			return true
		l11:
			position, tokenIndex = position11, tokenIndex11
			return false
		},
		/* 2 expression <- <(title_info (table_info / comment / empty_line)*)> */
		func() bool {
			position14, tokenIndex14 := position, tokenIndex
			{
				position15 := position
				if !_rules[ruletitle_info]() {
					goto l14
				}
			l16:
				{
					position17, tokenIndex17 := position, tokenIndex
					{
						position18, tokenIndex18 := position, tokenIndex
						if !_rules[ruletable_info]() {
							goto l19
						}
						goto l18
					l19:
						position, tokenIndex = position18, tokenIndex18
						if !_rules[rulecomment]() {
							goto l20
						}
						goto l18
					l20:
						position, tokenIndex = position18, tokenIndex18
						if !_rules[ruleempty_line]() {
							goto l17
						}
					}
				l18:
					goto l16
				l17:
					position, tokenIndex = position17, tokenIndex17
				}
				add(ruleexpression, position15)
			}
			return true
		l14:
			position, tokenIndex = position14, tokenIndex14
			return false
		},
		/* 3 title_info <- <('#' space* ('T' 'i' 't' 'l' 'e' ':') space* <title> Action2 newline)> */
		func() bool {
			position21, tokenIndex21 := position, tokenIndex
			{
				position22 := position
				if buffer[position] != rune('#') {
					goto l21
				}
				position++
			l23:
				{
					position24, tokenIndex24 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l24
					}
					goto l23
				l24:
					position, tokenIndex = position24, tokenIndex24
				}
				if buffer[position] != rune('T') {
					goto l21
				}
				position++
				if buffer[position] != rune('i') {
					goto l21
				}
				position++
				if buffer[position] != rune('t') {
					goto l21
				}
				position++
				if buffer[position] != rune('l') {
					goto l21
				}
				position++
				if buffer[position] != rune('e') {
					goto l21
				}
				position++
				if buffer[position] != rune(':') {
					goto l21
				}
				position++
			l25:
				{
					position26, tokenIndex26 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l26
					}
					goto l25
				l26:
					position, tokenIndex = position26, tokenIndex26
				}
				{
					position27 := position
					if !_rules[ruletitle]() {
						goto l21
					}
					add(rulePegText, position27)
				}
				if !_rules[ruleAction2]() {
					goto l21
				}
				if !_rules[rulenewline]() {
					goto l21
				}
				add(ruletitle_info, position22)
			}
			return true
		l21:
			position, tokenIndex = position21, tokenIndex21
			return false
		},
		/* 4 table_info <- <(table_name_info column_info* index_info*)> */
		func() bool {
			position28, tokenIndex28 := position, tokenIndex
			{
				position29 := position
				if !_rules[ruletable_name_info]() {
					goto l28
				}
			l30:
				{
					position31, tokenIndex31 := position, tokenIndex
					if !_rules[rulecolumn_info]() {
						goto l31
					}
					goto l30
				l31:
					position, tokenIndex = position31, tokenIndex31
				}
			l32:
				{
					position33, tokenIndex33 := position, tokenIndex
					if !_rules[ruleindex_info]() {
						goto l33
					}
					goto l32
				l33:
					position, tokenIndex = position33, tokenIndex33
				}
				add(ruletable_info, position29)
			}
			return true
		l28:
			position, tokenIndex = position28, tokenIndex28
			return false
		},
		/* 5 comment <- <(space* ('/' '/') comment_string newline)> */
		func() bool {
			position34, tokenIndex34 := position, tokenIndex
			{
				position35 := position
			l36:
				{
					position37, tokenIndex37 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l37
					}
					goto l36
				l37:
					position, tokenIndex = position37, tokenIndex37
				}
				if buffer[position] != rune('/') {
					goto l34
				}
				position++
				if buffer[position] != rune('/') {
					goto l34
				}
				position++
				if !_rules[rulecomment_string]() {
					goto l34
				}
				if !_rules[rulenewline]() {
					goto l34
				}
				add(rulecomment, position35)
			}
			return true
		l34:
			position, tokenIndex = position34, tokenIndex34
			return false
		},
		/* 6 empty_line <- <whitespace> */
		func() bool {
			position38, tokenIndex38 := position, tokenIndex
			{
				position39 := position
				if !_rules[rulewhitespace]() {
					goto l38
				}
				add(ruleempty_line, position39)
			}
			return true
		l38:
			position, tokenIndex = position38, tokenIndex38
			return false
		},
		/* 7 table_name_info <- <(<real_table_name> Action3 space* ('/' space* <table_name> Action4)? space* (groups_decl space*)? newline*)> */
		func() bool {
			position40, tokenIndex40 := position, tokenIndex
			{
				position41 := position
				{
					position42 := position
					if !_rules[rulereal_table_name]() {
						goto l40
					}
					add(rulePegText, position42)
				}
				if !_rules[ruleAction3]() {
					goto l40
				}
			l43:
				{
					position44, tokenIndex44 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l44
					}
					goto l43
				l44:
					position, tokenIndex = position44, tokenIndex44
				}
				{
					position45, tokenIndex45 := position, tokenIndex
					if buffer[position] != rune('/') {
						goto l45
					}
					position++
				l47:
					{
						position48, tokenIndex48 := position, tokenIndex
						if !_rules[rulespace]() {
							goto l48
						}
						goto l47
					l48:
						position, tokenIndex = position48, tokenIndex48
					}
					{
						position49 := position
						if !_rules[ruletable_name]() {
							goto l45
						}
						add(rulePegText, position49)
					}
					if !_rules[ruleAction4]() {
						goto l45
					}
					goto l46
				l45:
					position, tokenIndex = position45, tokenIndex45
				}
			l46:
			l50:
				{
					position51, tokenIndex51 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l51
					}
					goto l50
				l51:
					position, tokenIndex = position51, tokenIndex51
				}
				{
					position52, tokenIndex52 := position, tokenIndex
					if !_rules[rulegroups_decl]() {
						goto l52
					}
				l54:
					{
						position55, tokenIndex55 := position, tokenIndex
						if !_rules[rulespace]() {
							goto l55
						}
						goto l54
					l55:
						position, tokenIndex = position55, tokenIndex55
					}
					goto l53
				l52:
					position, tokenIndex = position52, tokenIndex52
				}
			l53:
			l56:
				{
					position57, tokenIndex57 := position, tokenIndex
					if !_rules[rulenewline]() {
						goto l57
					}
					goto l56
				l57:
					position, tokenIndex = position57, tokenIndex57
				}
				add(ruletable_name_info, position41)
			}
			return true
		l40:
			position, tokenIndex = position40, tokenIndex40
			return false
		},
		/* 8 column_info <- <(column_attribute (space* relation (space* relation)*)? (newline? column_comment)* newline?)> */
		func() bool {
			position58, tokenIndex58 := position, tokenIndex
			{
				position59 := position
				if !_rules[rulecolumn_attribute]() {
					goto l58
				}
				{
					position60, tokenIndex60 := position, tokenIndex
				l62:
					{
						position63, tokenIndex63 := position, tokenIndex
						if !_rules[rulespace]() {
							goto l63
						}
						goto l62
					l63:
						position, tokenIndex = position63, tokenIndex63
					}
					if !_rules[rulerelation]() {
						goto l60
					}
				l64:
					{
						position65, tokenIndex65 := position, tokenIndex
					l66:
						{
							position67, tokenIndex67 := position, tokenIndex
							if !_rules[rulespace]() {
								goto l67
							}
							goto l66
						l67:
							position, tokenIndex = position67, tokenIndex67
						}
						if !_rules[rulerelation]() {
							goto l65
						}
						goto l64
					l65:
						position, tokenIndex = position65, tokenIndex65
					}
					goto l61
				l60:
					position, tokenIndex = position60, tokenIndex60
				}
			l61:
			l68:
				{
					position69, tokenIndex69 := position, tokenIndex
					{
						position70, tokenIndex70 := position, tokenIndex
						if !_rules[rulenewline]() {
							goto l70
						}
						goto l71
					l70:
						position, tokenIndex = position70, tokenIndex70
					}
				l71:
					if !_rules[rulecolumn_comment]() {
						goto l69
					}
					goto l68
				l69:
					position, tokenIndex = position69, tokenIndex69
				}
				{
					position72, tokenIndex72 := position, tokenIndex
					if !_rules[rulenewline]() {
						goto l72
					}
					goto l73
				l72:
					position, tokenIndex = position72, tokenIndex72
				}
			l73:
				add(rulecolumn_info, position59)
			}
			return true
		l58:
			position, tokenIndex = position58, tokenIndex58
			return false
		},
		/* 9 column_attribute <- <(space+ (<pkey> Action5)? <real_column_name> Action6 ('/' <column_name> Action7)? space+ '[' <col_type> Action8 ']' (('[' notnull Action9 ']') / ('[' unique Action10 ']') / ('[' '=' <default> Action11 ']') / ('[' <erd> Action12 ']'))* newline?)> */
		func() bool {
			position74, tokenIndex74 := position, tokenIndex
			{
				position75 := position
				if !_rules[rulespace]() {
					goto l74
				}
			l76:
				{
					position77, tokenIndex77 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l77
					}
					goto l76
				l77:
					position, tokenIndex = position77, tokenIndex77
				}
				{
					position78, tokenIndex78 := position, tokenIndex
					{
						position80 := position
						if !_rules[rulepkey]() {
							goto l78
						}
						add(rulePegText, position80)
					}
					if !_rules[ruleAction5]() {
						goto l78
					}
					goto l79
				l78:
					position, tokenIndex = position78, tokenIndex78
				}
			l79:
				{
					position81 := position
					if !_rules[rulereal_column_name]() {
						goto l74
					}
					add(rulePegText, position81)
				}
				if !_rules[ruleAction6]() {
					goto l74
				}
				{
					position82, tokenIndex82 := position, tokenIndex
					if buffer[position] != rune('/') {
						goto l82
					}
					position++
					{
						position84 := position
						if !_rules[rulecolumn_name]() {
							goto l82
						}
						add(rulePegText, position84)
					}
					if !_rules[ruleAction7]() {
						goto l82
					}
					goto l83
				l82:
					position, tokenIndex = position82, tokenIndex82
				}
			l83:
				if !_rules[rulespace]() {
					goto l74
				}
			l85:
				{
					position86, tokenIndex86 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l86
					}
					goto l85
				l86:
					position, tokenIndex = position86, tokenIndex86
				}
				if buffer[position] != rune('[') {
					goto l74
				}
				position++
				{
					position87 := position
					if !_rules[rulecol_type]() {
						goto l74
					}
					add(rulePegText, position87)
				}
				if !_rules[ruleAction8]() {
					goto l74
				}
				if buffer[position] != rune(']') {
					goto l74
				}
				position++
			l88:
				{
					position89, tokenIndex89 := position, tokenIndex
					{
						position90, tokenIndex90 := position, tokenIndex
						if buffer[position] != rune('[') {
							goto l91
						}
						position++
						if !_rules[rulenotnull]() {
							goto l91
						}
						if !_rules[ruleAction9]() {
							goto l91
						}
						if buffer[position] != rune(']') {
							goto l91
						}
						position++
						goto l90
					l91:
						position, tokenIndex = position90, tokenIndex90
						if buffer[position] != rune('[') {
							goto l92
						}
						position++
						if !_rules[ruleunique]() {
							goto l92
						}
						if !_rules[ruleAction10]() {
							goto l92
						}
						if buffer[position] != rune(']') {
							goto l92
						}
						position++
						goto l90
					l92:
						position, tokenIndex = position90, tokenIndex90
						if buffer[position] != rune('[') {
							goto l93
						}
						position++
						if buffer[position] != rune('=') {
							goto l93
						}
						position++
						{
							position94 := position
							if !_rules[ruledefault]() {
								goto l93
							}
							add(rulePegText, position94)
						}
						if !_rules[ruleAction11]() {
							goto l93
						}
						if buffer[position] != rune(']') {
							goto l93
						}
						position++
						goto l90
					l93:
						position, tokenIndex = position90, tokenIndex90
						if buffer[position] != rune('[') {
							goto l89
						}
						position++
						{
							position95 := position
							if !_rules[ruleerd]() {
								goto l89
							}
							add(rulePegText, position95)
						}
						if !_rules[ruleAction12]() {
							goto l89
						}
						if buffer[position] != rune(']') {
							goto l89
						}
						position++
					}
				l90:
					goto l88
				l89:
					position, tokenIndex = position89, tokenIndex89
				}
				{
					position96, tokenIndex96 := position, tokenIndex
					if !_rules[rulenewline]() {
						goto l96
					}
					goto l97
				l96:
					position, tokenIndex = position96, tokenIndex96
				}
			l97:
				add(rulecolumn_attribute, position75)
			}
			return true
		l74:
			position, tokenIndex = position74, tokenIndex74
			return false
		},
		/* 10 relation <- <((<cardinality_left> Action13)? space* ('-' '-') space* (<cardinality_right> Action14 space)? space* <relation_point> Action15)> */
		func() bool {
			position98, tokenIndex98 := position, tokenIndex
			{
				position99 := position
				{
					position100, tokenIndex100 := position, tokenIndex
					{
						position102 := position
						if !_rules[rulecardinality_left]() {
							goto l100
						}
						add(rulePegText, position102)
					}
					if !_rules[ruleAction13]() {
						goto l100
					}
					goto l101
				l100:
					position, tokenIndex = position100, tokenIndex100
				}
			l101:
			l103:
				{
					position104, tokenIndex104 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l104
					}
					goto l103
				l104:
					position, tokenIndex = position104, tokenIndex104
				}
				if buffer[position] != rune('-') {
					goto l98
				}
				position++
				if buffer[position] != rune('-') {
					goto l98
				}
				position++
			l105:
				{
					position106, tokenIndex106 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l106
					}
					goto l105
				l106:
					position, tokenIndex = position106, tokenIndex106
				}
				{
					position107, tokenIndex107 := position, tokenIndex
					{
						position109 := position
						if !_rules[rulecardinality_right]() {
							goto l107
						}
						add(rulePegText, position109)
					}
					if !_rules[ruleAction14]() {
						goto l107
					}
					if !_rules[rulespace]() {
						goto l107
					}
					goto l108
				l107:
					position, tokenIndex = position107, tokenIndex107
				}
			l108:
			l110:
				{
					position111, tokenIndex111 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l111
					}
					goto l110
				l111:
					position, tokenIndex = position111, tokenIndex111
				}
				{
					position112 := position
					if !_rules[rulerelation_point]() {
						goto l98
					}
					add(rulePegText, position112)
				}
				if !_rules[ruleAction15]() {
					goto l98
				}
				add(rulerelation, position99)
			}
			return true
		l98:
			position, tokenIndex = position98, tokenIndex98
			return false
		},
		/* 11 column_comment <- <(space+ '#' space? <comment_string> Action16)> */
		func() bool {
			position113, tokenIndex113 := position, tokenIndex
			{
				position114 := position
				if !_rules[rulespace]() {
					goto l113
				}
			l115:
				{
					position116, tokenIndex116 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l116
					}
					goto l115
				l116:
					position, tokenIndex = position116, tokenIndex116
				}
				if buffer[position] != rune('#') {
					goto l113
				}
				position++
				{
					position117, tokenIndex117 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l117
					}
					goto l118
				l117:
					position, tokenIndex = position117, tokenIndex117
				}
			l118:
				{
					position119 := position
					if !_rules[rulecomment_string]() {
						goto l113
					}
					add(rulePegText, position119)
				}
				if !_rules[ruleAction16]() {
					goto l113
				}
				add(rulecolumn_comment, position114)
			}
			return true
		l113:
			position, tokenIndex = position113, tokenIndex113
			return false
		},
		/* 12 index_info <- <(space+ (('i' / 'I') ('n' / 'N') ('d' / 'D') ('e' / 'E') ('x' / 'X')) space+ <real_column_name> Action17 space+ '(' space* <real_column_name> Action18 (space* ',' space* <real_column_name> Action19 space*)* space* ')' (space+ ('u' 'n' 'i' 'q' 'u' 'e') Action20)? space* newline*)> */
		func() bool {
			position120, tokenIndex120 := position, tokenIndex
			{
				position121 := position
				if !_rules[rulespace]() {
					goto l120
				}
			l122:
				{
					position123, tokenIndex123 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l123
					}
					goto l122
				l123:
					position, tokenIndex = position123, tokenIndex123
				}
				{
					position124, tokenIndex124 := position, tokenIndex
					if buffer[position] != rune('i') {
						goto l125
					}
					position++
					goto l124
				l125:
					position, tokenIndex = position124, tokenIndex124
					if buffer[position] != rune('I') {
						goto l120
					}
					position++
				}
			l124:
				{
					position126, tokenIndex126 := position, tokenIndex
					if buffer[position] != rune('n') {
						goto l127
					}
					position++
					goto l126
				l127:
					position, tokenIndex = position126, tokenIndex126
					if buffer[position] != rune('N') {
						goto l120
					}
					position++
				}
			l126:
				{
					position128, tokenIndex128 := position, tokenIndex
					if buffer[position] != rune('d') {
						goto l129
					}
					position++
					goto l128
				l129:
					position, tokenIndex = position128, tokenIndex128
					if buffer[position] != rune('D') {
						goto l120
					}
					position++
				}
			l128:
				{
					position130, tokenIndex130 := position, tokenIndex
					if buffer[position] != rune('e') {
						goto l131
					}
					position++
					goto l130
				l131:
					position, tokenIndex = position130, tokenIndex130
					if buffer[position] != rune('E') {
						goto l120
					}
					position++
				}
			l130:
				{
					position132, tokenIndex132 := position, tokenIndex
					if buffer[position] != rune('x') {
						goto l133
					}
					position++
					goto l132
				l133:
					position, tokenIndex = position132, tokenIndex132
					if buffer[position] != rune('X') {
						goto l120
					}
					position++
				}
			l132:
				if !_rules[rulespace]() {
					goto l120
				}
			l134:
				{
					position135, tokenIndex135 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l135
					}
					goto l134
				l135:
					position, tokenIndex = position135, tokenIndex135
				}
				{
					position136 := position
					if !_rules[rulereal_column_name]() {
						goto l120
					}
					add(rulePegText, position136)
				}
				if !_rules[ruleAction17]() {
					goto l120
				}
				if !_rules[rulespace]() {
					goto l120
				}
			l137:
				{
					position138, tokenIndex138 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l138
					}
					goto l137
				l138:
					position, tokenIndex = position138, tokenIndex138
				}
				if buffer[position] != rune('(') {
					goto l120
				}
				position++
			l139:
				{
					position140, tokenIndex140 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l140
					}
					goto l139
				l140:
					position, tokenIndex = position140, tokenIndex140
				}
				{
					position141 := position
					if !_rules[rulereal_column_name]() {
						goto l120
					}
					add(rulePegText, position141)
				}
				if !_rules[ruleAction18]() {
					goto l120
				}
			l142:
				{
					position143, tokenIndex143 := position, tokenIndex
				l144:
					{
						position145, tokenIndex145 := position, tokenIndex
						if !_rules[rulespace]() {
							goto l145
						}
						goto l144
					l145:
						position, tokenIndex = position145, tokenIndex145
					}
					if buffer[position] != rune(',') {
						goto l143
					}
					position++
				l146:
					{
						position147, tokenIndex147 := position, tokenIndex
						if !_rules[rulespace]() {
							goto l147
						}
						goto l146
					l147:
						position, tokenIndex = position147, tokenIndex147
					}
					{
						position148 := position
						if !_rules[rulereal_column_name]() {
							goto l143
						}
						add(rulePegText, position148)
					}
					if !_rules[ruleAction19]() {
						goto l143
					}
				l149:
					{
						position150, tokenIndex150 := position, tokenIndex
						if !_rules[rulespace]() {
							goto l150
						}
						goto l149
					l150:
						position, tokenIndex = position150, tokenIndex150
					}
					goto l142
				l143:
					position, tokenIndex = position143, tokenIndex143
				}
			l151:
				{
					position152, tokenIndex152 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l152
					}
					goto l151
				l152:
					position, tokenIndex = position152, tokenIndex152
				}
				if buffer[position] != rune(')') {
					goto l120
				}
				position++
				{
					position153, tokenIndex153 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l153
					}
				l155:
					{
						position156, tokenIndex156 := position, tokenIndex
						if !_rules[rulespace]() {
							goto l156
						}
						goto l155
					l156:
						position, tokenIndex = position156, tokenIndex156
					}
					if buffer[position] != rune('u') {
						goto l153
					}
					position++
					if buffer[position] != rune('n') {
						goto l153
					}
					position++
					if buffer[position] != rune('i') {
						goto l153
					}
					position++
					if buffer[position] != rune('q') {
						goto l153
					}
					position++
					if buffer[position] != rune('u') {
						goto l153
					}
					position++
					if buffer[position] != rune('e') {
						goto l153
					}
					position++
					if !_rules[ruleAction20]() {
						goto l153
					}
					goto l154
				l153:
					position, tokenIndex = position153, tokenIndex153
				}
			l154:
			l157:
				{
					position158, tokenIndex158 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l158
					}
					goto l157
				l158:
					position, tokenIndex = position158, tokenIndex158
				}
			l159:
				{
					position160, tokenIndex160 := position, tokenIndex
					if !_rules[rulenewline]() {
						goto l160
					}
					goto l159
				l160:
					position, tokenIndex = position160, tokenIndex160
				}
				add(ruleindex_info, position121)
			}
			return true
		l120:
			position, tokenIndex = position120, tokenIndex120
			return false
		},
		/* 13 groups_decl <- <('@' 'g' 'r' 'o' 'u' 'p' 's' space* '[' space* <group_string> Action21 (space* ',' space* <group_string> Action22)* space* ']' Action23)> */
		func() bool {
			position161, tokenIndex161 := position, tokenIndex
			{
				position162 := position
				if buffer[position] != rune('@') {
					goto l161
				}
				position++
				if buffer[position] != rune('g') {
					goto l161
				}
				position++
				if buffer[position] != rune('r') {
					goto l161
				}
				position++
				if buffer[position] != rune('o') {
					goto l161
				}
				position++
				if buffer[position] != rune('u') {
					goto l161
				}
				position++
				if buffer[position] != rune('p') {
					goto l161
				}
				position++
				if buffer[position] != rune('s') {
					goto l161
				}
				position++
			l163:
				{
					position164, tokenIndex164 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l164
					}
					goto l163
				l164:
					position, tokenIndex = position164, tokenIndex164
				}
				if buffer[position] != rune('[') {
					goto l161
				}
				position++
			l165:
				{
					position166, tokenIndex166 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l166
					}
					goto l165
				l166:
					position, tokenIndex = position166, tokenIndex166
				}
				{
					position167 := position
					if !_rules[rulegroup_string]() {
						goto l161
					}
					add(rulePegText, position167)
				}
				if !_rules[ruleAction21]() {
					goto l161
				}
			l168:
				{
					position169, tokenIndex169 := position, tokenIndex
				l170:
					{
						position171, tokenIndex171 := position, tokenIndex
						if !_rules[rulespace]() {
							goto l171
						}
						goto l170
					l171:
						position, tokenIndex = position171, tokenIndex171
					}
					if buffer[position] != rune(',') {
						goto l169
					}
					position++
				l172:
					{
						position173, tokenIndex173 := position, tokenIndex
						if !_rules[rulespace]() {
							goto l173
						}
						goto l172
					l173:
						position, tokenIndex = position173, tokenIndex173
					}
					{
						position174 := position
						if !_rules[rulegroup_string]() {
							goto l169
						}
						add(rulePegText, position174)
					}
					if !_rules[ruleAction22]() {
						goto l169
					}
					goto l168
				l169:
					position, tokenIndex = position169, tokenIndex169
				}
			l175:
				{
					position176, tokenIndex176 := position, tokenIndex
					if !_rules[rulespace]() {
						goto l176
					}
					goto l175
				l176:
					position, tokenIndex = position176, tokenIndex176
				}
				if buffer[position] != rune(']') {
					goto l161
				}
				position++
				if !_rules[ruleAction23]() {
					goto l161
				}
				add(rulegroups_decl, position162)
			}
			return true
		l161:
			position, tokenIndex = position161, tokenIndex161
			return false
		},
		/* 14 group_string <- <('"' (!('\r' / '\n' / '"') .)+ '"')> */
		func() bool {
			position177, tokenIndex177 := position, tokenIndex
			{
				position178 := position
				if buffer[position] != rune('"') {
					goto l177
				}
				position++
				{
					position181, tokenIndex181 := position, tokenIndex
					{
						position182, tokenIndex182 := position, tokenIndex
						if buffer[position] != rune('\r') {
							goto l183
						}
						position++
						goto l182
					l183:
						position, tokenIndex = position182, tokenIndex182
						if buffer[position] != rune('\n') {
							goto l184
						}
						position++
						goto l182
					l184:
						position, tokenIndex = position182, tokenIndex182
						if buffer[position] != rune('"') {
							goto l181
						}
						position++
					}
				l182:
					goto l177
				l181:
					position, tokenIndex = position181, tokenIndex181
				}
				if !matchDot() {
					goto l177
				}
			l179:
				{
					position180, tokenIndex180 := position, tokenIndex
					{
						position185, tokenIndex185 := position, tokenIndex
						{
							position186, tokenIndex186 := position, tokenIndex
							if buffer[position] != rune('\r') {
								goto l187
							}
							position++
							goto l186
						l187:
							position, tokenIndex = position186, tokenIndex186
							if buffer[position] != rune('\n') {
								goto l188
							}
							position++
							goto l186
						l188:
							position, tokenIndex = position186, tokenIndex186
							if buffer[position] != rune('"') {
								goto l185
							}
							position++
						}
					l186:
						goto l180
					l185:
						position, tokenIndex = position185, tokenIndex185
					}
					if !matchDot() {
						goto l180
					}
					goto l179
				l180:
					position, tokenIndex = position180, tokenIndex180
				}
				if buffer[position] != rune('"') {
					goto l177
				}
				position++
				add(rulegroup_string, position178)
			}
			return true
		l177:
			position, tokenIndex = position177, tokenIndex177
			return false
		},
		/* 15 title <- <(!('\r' / '\n') .)+> */
		func() bool {
			position189, tokenIndex189 := position, tokenIndex
			{
				position190 := position
				{
					position193, tokenIndex193 := position, tokenIndex
					{
						position194, tokenIndex194 := position, tokenIndex
						if buffer[position] != rune('\r') {
							goto l195
						}
						position++
						goto l194
					l195:
						position, tokenIndex = position194, tokenIndex194
						if buffer[position] != rune('\n') {
							goto l193
						}
						position++
					}
				l194:
					goto l189
				l193:
					position, tokenIndex = position193, tokenIndex193
				}
				if !matchDot() {
					goto l189
				}
			l191:
				{
					position192, tokenIndex192 := position, tokenIndex
					{
						position196, tokenIndex196 := position, tokenIndex
						{
							position197, tokenIndex197 := position, tokenIndex
							if buffer[position] != rune('\r') {
								goto l198
							}
							position++
							goto l197
						l198:
							position, tokenIndex = position197, tokenIndex197
							if buffer[position] != rune('\n') {
								goto l196
							}
							position++
						}
					l197:
						goto l192
					l196:
						position, tokenIndex = position196, tokenIndex196
					}
					if !matchDot() {
						goto l192
					}
					goto l191
				l192:
					position, tokenIndex = position192, tokenIndex192
				}
				add(ruletitle, position190)
			}
			return true
		l189:
			position, tokenIndex = position189, tokenIndex189
			return false
		},
		/* 16 comment_string <- <(!('\r' / '\n') .)*> */
		func() bool {
			{
				position200 := position
			l201:
				{
					position202, tokenIndex202 := position, tokenIndex
					{
						position203, tokenIndex203 := position, tokenIndex
						{
							position204, tokenIndex204 := position, tokenIndex
							if buffer[position] != rune('\r') {
								goto l205
							}
							position++
							goto l204
						l205:
							position, tokenIndex = position204, tokenIndex204
							if buffer[position] != rune('\n') {
								goto l203
							}
							position++
						}
					l204:
						goto l202
					l203:
						position, tokenIndex = position203, tokenIndex203
					}
					if !matchDot() {
						goto l202
					}
					goto l201
				l202:
					position, tokenIndex = position202, tokenIndex202
				}
				add(rulecomment_string, position200)
			}
			return true
		},
		/* 17 whitespace <- <(' ' / '\t' / '\r' / '\n')+> */
		func() bool {
			position206, tokenIndex206 := position, tokenIndex
			{
				position207 := position
				{
					position210, tokenIndex210 := position, tokenIndex
					if buffer[position] != rune(' ') {
						goto l211
					}
					position++
					goto l210
				l211:
					position, tokenIndex = position210, tokenIndex210
					if buffer[position] != rune('\t') {
						goto l212
					}
					position++
					goto l210
				l212:
					position, tokenIndex = position210, tokenIndex210
					if buffer[position] != rune('\r') {
						goto l213
					}
					position++
					goto l210
				l213:
					position, tokenIndex = position210, tokenIndex210
					if buffer[position] != rune('\n') {
						goto l206
					}
					position++
				}
			l210:
			l208:
				{
					position209, tokenIndex209 := position, tokenIndex
					{
						position214, tokenIndex214 := position, tokenIndex
						if buffer[position] != rune(' ') {
							goto l215
						}
						position++
						goto l214
					l215:
						position, tokenIndex = position214, tokenIndex214
						if buffer[position] != rune('\t') {
							goto l216
						}
						position++
						goto l214
					l216:
						position, tokenIndex = position214, tokenIndex214
						if buffer[position] != rune('\r') {
							goto l217
						}
						position++
						goto l214
					l217:
						position, tokenIndex = position214, tokenIndex214
						if buffer[position] != rune('\n') {
							goto l209
						}
						position++
					}
				l214:
					goto l208
				l209:
					position, tokenIndex = position209, tokenIndex209
				}
				add(rulewhitespace, position207)
			}
			return true
		l206:
			position, tokenIndex = position206, tokenIndex206
			return false
		},
		/* 18 newline <- <('\r' / '\n')+> */
		func() bool {
			position218, tokenIndex218 := position, tokenIndex
			{
				position219 := position
				{
					position222, tokenIndex222 := position, tokenIndex
					if buffer[position] != rune('\r') {
						goto l223
					}
					position++
					goto l222
				l223:
					position, tokenIndex = position222, tokenIndex222
					if buffer[position] != rune('\n') {
						goto l218
					}
					position++
				}
			l222:
			l220:
				{
					position221, tokenIndex221 := position, tokenIndex
					{
						position224, tokenIndex224 := position, tokenIndex
						if buffer[position] != rune('\r') {
							goto l225
						}
						position++
						goto l224
					l225:
						position, tokenIndex = position224, tokenIndex224
						if buffer[position] != rune('\n') {
							goto l221
						}
						position++
					}
				l224:
					goto l220
				l221:
					position, tokenIndex = position221, tokenIndex221
				}
				add(rulenewline, position219)
			}
			return true
		l218:
			position, tokenIndex = position218, tokenIndex218
			return false
		},
		/* 19 space <- <(' ' / '\t')+> */
		func() bool {
			position226, tokenIndex226 := position, tokenIndex
			{
				position227 := position
				{
					position230, tokenIndex230 := position, tokenIndex
					if buffer[position] != rune(' ') {
						goto l231
					}
					position++
					goto l230
				l231:
					position, tokenIndex = position230, tokenIndex230
					if buffer[position] != rune('\t') {
						goto l226
					}
					position++
				}
			l230:
			l228:
				{
					position229, tokenIndex229 := position, tokenIndex
					{
						position232, tokenIndex232 := position, tokenIndex
						if buffer[position] != rune(' ') {
							goto l233
						}
						position++
						goto l232
					l233:
						position, tokenIndex = position232, tokenIndex232
						if buffer[position] != rune('\t') {
							goto l229
						}
						position++
					}
				l232:
					goto l228
				l229:
					position, tokenIndex = position229, tokenIndex229
				}
				add(rulespace, position227)
			}
			return true
		l226:
			position, tokenIndex = position226, tokenIndex226
			return false
		},
		/* 20 notnull <- <('N' 'N')> */
		func() bool {
			position234, tokenIndex234 := position, tokenIndex
			{
				position235 := position
				if buffer[position] != rune('N') {
					goto l234
				}
				position++
				if buffer[position] != rune('N') {
					goto l234
				}
				position++
				add(rulenotnull, position235)
			}
			return true
		l234:
			position, tokenIndex = position234, tokenIndex234
			return false
		},
		/* 21 unique <- <'U'> */
		func() bool {
			position236, tokenIndex236 := position, tokenIndex
			{
				position237 := position
				if buffer[position] != rune('U') {
					goto l236
				}
				position++
				add(ruleunique, position237)
			}
			return true
		l236:
			position, tokenIndex = position236, tokenIndex236
			return false
		},
		/* 22 erd <- <('-' 'e' 'r' 'd')> */
		func() bool {
			position238, tokenIndex238 := position, tokenIndex
			{
				position239 := position
				if buffer[position] != rune('-') {
					goto l238
				}
				position++
				if buffer[position] != rune('e') {
					goto l238
				}
				position++
				if buffer[position] != rune('r') {
					goto l238
				}
				position++
				if buffer[position] != rune('d') {
					goto l238
				}
				position++
				add(ruleerd, position239)
			}
			return true
		l238:
			position, tokenIndex = position238, tokenIndex238
			return false
		},
		/* 23 real_table_name <- <([a-z] / [A-Z] / [0-9] / '_')+> */
		func() bool {
			position240, tokenIndex240 := position, tokenIndex
			{
				position241 := position
				{
					position244, tokenIndex244 := position, tokenIndex
					if c := buffer[position]; c < rune('a') || c > rune('z') {
						goto l245
					}
					position++
					goto l244
				l245:
					position, tokenIndex = position244, tokenIndex244
					if c := buffer[position]; c < rune('A') || c > rune('Z') {
						goto l246
					}
					position++
					goto l244
				l246:
					position, tokenIndex = position244, tokenIndex244
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l247
					}
					position++
					goto l244
				l247:
					position, tokenIndex = position244, tokenIndex244
					if buffer[position] != rune('_') {
						goto l240
					}
					position++
				}
			l244:
			l242:
				{
					position243, tokenIndex243 := position, tokenIndex
					{
						position248, tokenIndex248 := position, tokenIndex
						if c := buffer[position]; c < rune('a') || c > rune('z') {
							goto l249
						}
						position++
						goto l248
					l249:
						position, tokenIndex = position248, tokenIndex248
						if c := buffer[position]; c < rune('A') || c > rune('Z') {
							goto l250
						}
						position++
						goto l248
					l250:
						position, tokenIndex = position248, tokenIndex248
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l251
						}
						position++
						goto l248
					l251:
						position, tokenIndex = position248, tokenIndex248
						if buffer[position] != rune('_') {
							goto l243
						}
						position++
					}
				l248:
					goto l242
				l243:
					position, tokenIndex = position243, tokenIndex243
				}
				add(rulereal_table_name, position241)
			}
			return true
		l240:
			position, tokenIndex = position240, tokenIndex240
			return false
		},
		/* 24 table_name <- <(('"' (!('\t' / '\r' / '\n' / '"') .)+ '"') / (!('\t' / '\r' / '\n' / '/' / ' ') .)+)> */
		func() bool {
			position252, tokenIndex252 := position, tokenIndex
			{
				position253 := position
				{
					position254, tokenIndex254 := position, tokenIndex
					if buffer[position] != rune('"') {
						goto l255
					}
					position++
					{
						position258, tokenIndex258 := position, tokenIndex
						{
							position259, tokenIndex259 := position, tokenIndex
							if buffer[position] != rune('\t') {
								goto l260
							}
							position++
							goto l259
						l260:
							position, tokenIndex = position259, tokenIndex259
							if buffer[position] != rune('\r') {
								goto l261
							}
							position++
							goto l259
						l261:
							position, tokenIndex = position259, tokenIndex259
							if buffer[position] != rune('\n') {
								goto l262
							}
							position++
							goto l259
						l262:
							position, tokenIndex = position259, tokenIndex259
							if buffer[position] != rune('"') {
								goto l258
							}
							position++
						}
					l259:
						goto l255
					l258:
						position, tokenIndex = position258, tokenIndex258
					}
					if !matchDot() {
						goto l255
					}
				l256:
					{
						position257, tokenIndex257 := position, tokenIndex
						{
							position263, tokenIndex263 := position, tokenIndex
							{
								position264, tokenIndex264 := position, tokenIndex
								if buffer[position] != rune('\t') {
									goto l265
								}
								position++
								goto l264
							l265:
								position, tokenIndex = position264, tokenIndex264
								if buffer[position] != rune('\r') {
									goto l266
								}
								position++
								goto l264
							l266:
								position, tokenIndex = position264, tokenIndex264
								if buffer[position] != rune('\n') {
									goto l267
								}
								position++
								goto l264
							l267:
								position, tokenIndex = position264, tokenIndex264
								if buffer[position] != rune('"') {
									goto l263
								}
								position++
							}
						l264:
							goto l257
						l263:
							position, tokenIndex = position263, tokenIndex263
						}
						if !matchDot() {
							goto l257
						}
						goto l256
					l257:
						position, tokenIndex = position257, tokenIndex257
					}
					if buffer[position] != rune('"') {
						goto l255
					}
					position++
					goto l254
				l255:
					position, tokenIndex = position254, tokenIndex254
					{
						position270, tokenIndex270 := position, tokenIndex
						{
							position271, tokenIndex271 := position, tokenIndex
							if buffer[position] != rune('\t') {
								goto l272
							}
							position++
							goto l271
						l272:
							position, tokenIndex = position271, tokenIndex271
							if buffer[position] != rune('\r') {
								goto l273
							}
							position++
							goto l271
						l273:
							position, tokenIndex = position271, tokenIndex271
							if buffer[position] != rune('\n') {
								goto l274
							}
							position++
							goto l271
						l274:
							position, tokenIndex = position271, tokenIndex271
							if buffer[position] != rune('/') {
								goto l275
							}
							position++
							goto l271
						l275:
							position, tokenIndex = position271, tokenIndex271
							if buffer[position] != rune(' ') {
								goto l270
							}
							position++
						}
					l271:
						goto l252
					l270:
						position, tokenIndex = position270, tokenIndex270
					}
					if !matchDot() {
						goto l252
					}
				l268:
					{
						position269, tokenIndex269 := position, tokenIndex
						{
							position276, tokenIndex276 := position, tokenIndex
							{
								position277, tokenIndex277 := position, tokenIndex
								if buffer[position] != rune('\t') {
									goto l278
								}
								position++
								goto l277
							l278:
								position, tokenIndex = position277, tokenIndex277
								if buffer[position] != rune('\r') {
									goto l279
								}
								position++
								goto l277
							l279:
								position, tokenIndex = position277, tokenIndex277
								if buffer[position] != rune('\n') {
									goto l280
								}
								position++
								goto l277
							l280:
								position, tokenIndex = position277, tokenIndex277
								if buffer[position] != rune('/') {
									goto l281
								}
								position++
								goto l277
							l281:
								position, tokenIndex = position277, tokenIndex277
								if buffer[position] != rune(' ') {
									goto l276
								}
								position++
							}
						l277:
							goto l269
						l276:
							position, tokenIndex = position276, tokenIndex276
						}
						if !matchDot() {
							goto l269
						}
						goto l268
					l269:
						position, tokenIndex = position269, tokenIndex269
					}
				}
			l254:
				add(ruletable_name, position253)
			}
			return true
		l252:
			position, tokenIndex = position252, tokenIndex252
			return false
		},
		/* 25 real_column_name <- <([a-z] / [A-Z] / [0-9] / '_')+> */
		func() bool {
			position282, tokenIndex282 := position, tokenIndex
			{
				position283 := position
				{
					position286, tokenIndex286 := position, tokenIndex
					if c := buffer[position]; c < rune('a') || c > rune('z') {
						goto l287
					}
					position++
					goto l286
				l287:
					position, tokenIndex = position286, tokenIndex286
					if c := buffer[position]; c < rune('A') || c > rune('Z') {
						goto l288
					}
					position++
					goto l286
				l288:
					position, tokenIndex = position286, tokenIndex286
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l289
					}
					position++
					goto l286
				l289:
					position, tokenIndex = position286, tokenIndex286
					if buffer[position] != rune('_') {
						goto l282
					}
					position++
				}
			l286:
			l284:
				{
					position285, tokenIndex285 := position, tokenIndex
					{
						position290, tokenIndex290 := position, tokenIndex
						if c := buffer[position]; c < rune('a') || c > rune('z') {
							goto l291
						}
						position++
						goto l290
					l291:
						position, tokenIndex = position290, tokenIndex290
						if c := buffer[position]; c < rune('A') || c > rune('Z') {
							goto l292
						}
						position++
						goto l290
					l292:
						position, tokenIndex = position290, tokenIndex290
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l293
						}
						position++
						goto l290
					l293:
						position, tokenIndex = position290, tokenIndex290
						if buffer[position] != rune('_') {
							goto l285
						}
						position++
					}
				l290:
					goto l284
				l285:
					position, tokenIndex = position285, tokenIndex285
				}
				add(rulereal_column_name, position283)
			}
			return true
		l282:
			position, tokenIndex = position282, tokenIndex282
			return false
		},
		/* 26 column_name <- <(('"' (!('\t' / '\r' / '\n' / '"') .)+ '"') / (!('\t' / '\r' / '\n' / '/' / ' ') .)+)> */
		func() bool {
			position294, tokenIndex294 := position, tokenIndex
			{
				position295 := position
				{
					position296, tokenIndex296 := position, tokenIndex
					if buffer[position] != rune('"') {
						goto l297
					}
					position++
					{
						position300, tokenIndex300 := position, tokenIndex
						{
							position301, tokenIndex301 := position, tokenIndex
							if buffer[position] != rune('\t') {
								goto l302
							}
							position++
							goto l301
						l302:
							position, tokenIndex = position301, tokenIndex301
							if buffer[position] != rune('\r') {
								goto l303
							}
							position++
							goto l301
						l303:
							position, tokenIndex = position301, tokenIndex301
							if buffer[position] != rune('\n') {
								goto l304
							}
							position++
							goto l301
						l304:
							position, tokenIndex = position301, tokenIndex301
							if buffer[position] != rune('"') {
								goto l300
							}
							position++
						}
					l301:
						goto l297
					l300:
						position, tokenIndex = position300, tokenIndex300
					}
					if !matchDot() {
						goto l297
					}
				l298:
					{
						position299, tokenIndex299 := position, tokenIndex
						{
							position305, tokenIndex305 := position, tokenIndex
							{
								position306, tokenIndex306 := position, tokenIndex
								if buffer[position] != rune('\t') {
									goto l307
								}
								position++
								goto l306
							l307:
								position, tokenIndex = position306, tokenIndex306
								if buffer[position] != rune('\r') {
									goto l308
								}
								position++
								goto l306
							l308:
								position, tokenIndex = position306, tokenIndex306
								if buffer[position] != rune('\n') {
									goto l309
								}
								position++
								goto l306
							l309:
								position, tokenIndex = position306, tokenIndex306
								if buffer[position] != rune('"') {
									goto l305
								}
								position++
							}
						l306:
							goto l299
						l305:
							position, tokenIndex = position305, tokenIndex305
						}
						if !matchDot() {
							goto l299
						}
						goto l298
					l299:
						position, tokenIndex = position299, tokenIndex299
					}
					if buffer[position] != rune('"') {
						goto l297
					}
					position++
					goto l296
				l297:
					position, tokenIndex = position296, tokenIndex296
					{
						position312, tokenIndex312 := position, tokenIndex
						{
							position313, tokenIndex313 := position, tokenIndex
							if buffer[position] != rune('\t') {
								goto l314
							}
							position++
							goto l313
						l314:
							position, tokenIndex = position313, tokenIndex313
							if buffer[position] != rune('\r') {
								goto l315
							}
							position++
							goto l313
						l315:
							position, tokenIndex = position313, tokenIndex313
							if buffer[position] != rune('\n') {
								goto l316
							}
							position++
							goto l313
						l316:
							position, tokenIndex = position313, tokenIndex313
							if buffer[position] != rune('/') {
								goto l317
							}
							position++
							goto l313
						l317:
							position, tokenIndex = position313, tokenIndex313
							if buffer[position] != rune(' ') {
								goto l312
							}
							position++
						}
					l313:
						goto l294
					l312:
						position, tokenIndex = position312, tokenIndex312
					}
					if !matchDot() {
						goto l294
					}
				l310:
					{
						position311, tokenIndex311 := position, tokenIndex
						{
							position318, tokenIndex318 := position, tokenIndex
							{
								position319, tokenIndex319 := position, tokenIndex
								if buffer[position] != rune('\t') {
									goto l320
								}
								position++
								goto l319
							l320:
								position, tokenIndex = position319, tokenIndex319
								if buffer[position] != rune('\r') {
									goto l321
								}
								position++
								goto l319
							l321:
								position, tokenIndex = position319, tokenIndex319
								if buffer[position] != rune('\n') {
									goto l322
								}
								position++
								goto l319
							l322:
								position, tokenIndex = position319, tokenIndex319
								if buffer[position] != rune('/') {
									goto l323
								}
								position++
								goto l319
							l323:
								position, tokenIndex = position319, tokenIndex319
								if buffer[position] != rune(' ') {
									goto l318
								}
								position++
							}
						l319:
							goto l311
						l318:
							position, tokenIndex = position318, tokenIndex318
						}
						if !matchDot() {
							goto l311
						}
						goto l310
					l311:
						position, tokenIndex = position311, tokenIndex311
					}
				}
			l296:
				add(rulecolumn_name, position295)
			}
			return true
		l294:
			position, tokenIndex = position294, tokenIndex294
			return false
		},
		/* 27 relation_point <- <([a-z] / [A-Z] / [0-9] / '_' / '.')+> */
		func() bool {
			position324, tokenIndex324 := position, tokenIndex
			{
				position325 := position
				{
					position328, tokenIndex328 := position, tokenIndex
					if c := buffer[position]; c < rune('a') || c > rune('z') {
						goto l329
					}
					position++
					goto l328
				l329:
					position, tokenIndex = position328, tokenIndex328
					if c := buffer[position]; c < rune('A') || c > rune('Z') {
						goto l330
					}
					position++
					goto l328
				l330:
					position, tokenIndex = position328, tokenIndex328
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l331
					}
					position++
					goto l328
				l331:
					position, tokenIndex = position328, tokenIndex328
					if buffer[position] != rune('_') {
						goto l332
					}
					position++
					goto l328
				l332:
					position, tokenIndex = position328, tokenIndex328
					if buffer[position] != rune('.') {
						goto l324
					}
					position++
				}
			l328:
			l326:
				{
					position327, tokenIndex327 := position, tokenIndex
					{
						position333, tokenIndex333 := position, tokenIndex
						if c := buffer[position]; c < rune('a') || c > rune('z') {
							goto l334
						}
						position++
						goto l333
					l334:
						position, tokenIndex = position333, tokenIndex333
						if c := buffer[position]; c < rune('A') || c > rune('Z') {
							goto l335
						}
						position++
						goto l333
					l335:
						position, tokenIndex = position333, tokenIndex333
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l336
						}
						position++
						goto l333
					l336:
						position, tokenIndex = position333, tokenIndex333
						if buffer[position] != rune('_') {
							goto l337
						}
						position++
						goto l333
					l337:
						position, tokenIndex = position333, tokenIndex333
						if buffer[position] != rune('.') {
							goto l327
						}
						position++
					}
				l333:
					goto l326
				l327:
					position, tokenIndex = position327, tokenIndex327
				}
				add(rulerelation_point, position325)
			}
			return true
		l324:
			position, tokenIndex = position324, tokenIndex324
			return false
		},
		/* 28 pkey <- <('+' / '*')> */
		func() bool {
			position338, tokenIndex338 := position, tokenIndex
			{
				position339 := position
				{
					position340, tokenIndex340 := position, tokenIndex
					if buffer[position] != rune('+') {
						goto l341
					}
					position++
					goto l340
				l341:
					position, tokenIndex = position340, tokenIndex340
					if buffer[position] != rune('*') {
						goto l338
					}
					position++
				}
			l340:
				add(rulepkey, position339)
			}
			return true
		l338:
			position, tokenIndex = position338, tokenIndex338
			return false
		},
		/* 29 col_type <- <([a-z] / [A-Z] / [0-9] / '_' / '(' / ')' / ' ' / '.' / ',')+> */
		func() bool {
			position342, tokenIndex342 := position, tokenIndex
			{
				position343 := position
				{
					position346, tokenIndex346 := position, tokenIndex
					if c := buffer[position]; c < rune('a') || c > rune('z') {
						goto l347
					}
					position++
					goto l346
				l347:
					position, tokenIndex = position346, tokenIndex346
					if c := buffer[position]; c < rune('A') || c > rune('Z') {
						goto l348
					}
					position++
					goto l346
				l348:
					position, tokenIndex = position346, tokenIndex346
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l349
					}
					position++
					goto l346
				l349:
					position, tokenIndex = position346, tokenIndex346
					if buffer[position] != rune('_') {
						goto l350
					}
					position++
					goto l346
				l350:
					position, tokenIndex = position346, tokenIndex346
					if buffer[position] != rune('(') {
						goto l351
					}
					position++
					goto l346
				l351:
					position, tokenIndex = position346, tokenIndex346
					if buffer[position] != rune(')') {
						goto l352
					}
					position++
					goto l346
				l352:
					position, tokenIndex = position346, tokenIndex346
					if buffer[position] != rune(' ') {
						goto l353
					}
					position++
					goto l346
				l353:
					position, tokenIndex = position346, tokenIndex346
					if buffer[position] != rune('.') {
						goto l354
					}
					position++
					goto l346
				l354:
					position, tokenIndex = position346, tokenIndex346
					if buffer[position] != rune(',') {
						goto l342
					}
					position++
				}
			l346:
			l344:
				{
					position345, tokenIndex345 := position, tokenIndex
					{
						position355, tokenIndex355 := position, tokenIndex
						if c := buffer[position]; c < rune('a') || c > rune('z') {
							goto l356
						}
						position++
						goto l355
					l356:
						position, tokenIndex = position355, tokenIndex355
						if c := buffer[position]; c < rune('A') || c > rune('Z') {
							goto l357
						}
						position++
						goto l355
					l357:
						position, tokenIndex = position355, tokenIndex355
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l358
						}
						position++
						goto l355
					l358:
						position, tokenIndex = position355, tokenIndex355
						if buffer[position] != rune('_') {
							goto l359
						}
						position++
						goto l355
					l359:
						position, tokenIndex = position355, tokenIndex355
						if buffer[position] != rune('(') {
							goto l360
						}
						position++
						goto l355
					l360:
						position, tokenIndex = position355, tokenIndex355
						if buffer[position] != rune(')') {
							goto l361
						}
						position++
						goto l355
					l361:
						position, tokenIndex = position355, tokenIndex355
						if buffer[position] != rune(' ') {
							goto l362
						}
						position++
						goto l355
					l362:
						position, tokenIndex = position355, tokenIndex355
						if buffer[position] != rune('.') {
							goto l363
						}
						position++
						goto l355
					l363:
						position, tokenIndex = position355, tokenIndex355
						if buffer[position] != rune(',') {
							goto l345
						}
						position++
					}
				l355:
					goto l344
				l345:
					position, tokenIndex = position345, tokenIndex345
				}
				add(rulecol_type, position343)
			}
			return true
		l342:
			position, tokenIndex = position342, tokenIndex342
			return false
		},
		/* 30 default <- <((!('\r' / '\n' / ']') .) / ('\\' ']'))*> */
		func() bool {
			{
				position365 := position
			l366:
				{
					position367, tokenIndex367 := position, tokenIndex
					{
						position368, tokenIndex368 := position, tokenIndex
						{
							position370, tokenIndex370 := position, tokenIndex
							{
								position371, tokenIndex371 := position, tokenIndex
								if buffer[position] != rune('\r') {
									goto l372
								}
								position++
								goto l371
							l372:
								position, tokenIndex = position371, tokenIndex371
								if buffer[position] != rune('\n') {
									goto l373
								}
								position++
								goto l371
							l373:
								position, tokenIndex = position371, tokenIndex371
								if buffer[position] != rune(']') {
									goto l370
								}
								position++
							}
						l371:
							goto l369
						l370:
							position, tokenIndex = position370, tokenIndex370
						}
						if !matchDot() {
							goto l369
						}
						goto l368
					l369:
						position, tokenIndex = position368, tokenIndex368
						if buffer[position] != rune('\\') {
							goto l367
						}
						position++
						if buffer[position] != rune(']') {
							goto l367
						}
						position++
					}
				l368:
					goto l366
				l367:
					position, tokenIndex = position367, tokenIndex367
				}
				add(ruledefault, position365)
			}
			return true
		},
		/* 31 cardinality_right <- <cardinality> */
		func() bool {
			position374, tokenIndex374 := position, tokenIndex
			{
				position375 := position
				if !_rules[rulecardinality]() {
					goto l374
				}
				add(rulecardinality_right, position375)
			}
			return true
		l374:
			position, tokenIndex = position374, tokenIndex374
			return false
		},
		/* 32 cardinality_left <- <cardinality> */
		func() bool {
			position376, tokenIndex376 := position, tokenIndex
			{
				position377 := position
				if !_rules[rulecardinality]() {
					goto l376
				}
				add(rulecardinality_left, position377)
			}
			return true
		l376:
			position, tokenIndex = position376, tokenIndex376
			return false
		},
		/* 33 cardinality <- <(('0' / '1' / '*') (. . ('0' / '1' / '*'))?)> */
		func() bool {
			position378, tokenIndex378 := position, tokenIndex
			{
				position379 := position
				{
					position380, tokenIndex380 := position, tokenIndex
					if buffer[position] != rune('0') {
						goto l381
					}
					position++
					goto l380
				l381:
					position, tokenIndex = position380, tokenIndex380
					if buffer[position] != rune('1') {
						goto l382
					}
					position++
					goto l380
				l382:
					position, tokenIndex = position380, tokenIndex380
					if buffer[position] != rune('*') {
						goto l378
					}
					position++
				}
			l380:
				{
					position383, tokenIndex383 := position, tokenIndex
					if !matchDot() {
						goto l383
					}
					if !matchDot() {
						goto l383
					}
					{
						position385, tokenIndex385 := position, tokenIndex
						if buffer[position] != rune('0') {
							goto l386
						}
						position++
						goto l385
					l386:
						position, tokenIndex = position385, tokenIndex385
						if buffer[position] != rune('1') {
							goto l387
						}
						position++
						goto l385
					l387:
						position, tokenIndex = position385, tokenIndex385
						if buffer[position] != rune('*') {
							goto l383
						}
						position++
					}
				l385:
					goto l384
				l383:
					position, tokenIndex = position383, tokenIndex383
				}
			l384:
				add(rulecardinality, position379)
			}
			return true
		l378:
			position, tokenIndex = position378, tokenIndex378
			return false
		},
		nil,
		/* 36 Action0 <- <{p.Err(begin, buffer)}> */
		func() bool {
			{
				add(ruleAction0, position)
			}
			return true
		},
		/* 37 Action1 <- <{p.Err(begin, buffer)}> */
		func() bool {
			{
				add(ruleAction1, position)
			}
			return true
		},
		/* 38 Action2 <- <{p.setTitle(text)}> */
		func() bool {
			{
				add(ruleAction2, position)
			}
			return true
		},
		/* 39 Action3 <- <{p.addTableTitleReal(text)}> */
		func() bool {
			{
				add(ruleAction3, position)
			}
			return true
		},
		/* 40 Action4 <- <{p.addTableTitle(text)}> */
		func() bool {
			{
				add(ruleAction4, position)
			}
			return true
		},
		/* 41 Action5 <- <{ p.addPrimaryKey(text) }> */
		func() bool {
			{
				add(ruleAction5, position)
			}
			return true
		},
		/* 42 Action6 <- <{ p.setColumnNameReal(text) }> */
		func() bool {
			{
				add(ruleAction6, position)
			}
			return true
		},
		/* 43 Action7 <- <{ p.setColumnName(text) }> */
		func() bool {
			{
				add(ruleAction7, position)
			}
			return true
		},
		/* 44 Action8 <- <{ p.addColumnType(text) }> */
		func() bool {
			{
				add(ruleAction8, position)
			}
			return true
		},
		/* 45 Action9 <- <{ p.setNotNull() }> */
		func() bool {
			{
				add(ruleAction9, position)
			}
			return true
		},
		/* 46 Action10 <- <{ p.setUnique() }> */
		func() bool {
			{
				add(ruleAction10, position)
			}
			return true
		},
		/* 47 Action11 <- <{ p.setColumnDefault(text) }> */
		func() bool {
			{
				add(ruleAction11, position)
			}
			return true
		},
		/* 48 Action12 <- <{ p.setWithoutErd() }> */
		func() bool {
			{
				add(ruleAction12, position)
			}
			return true
		},
		/* 49 Action13 <- <{ p.setRelationSource(text) }> */
		func() bool {
			{
				add(ruleAction13, position)
			}
			return true
		},
		/* 50 Action14 <- <{ p.setRelationDestination(text) }> */
		func() bool {
			{
				add(ruleAction14, position)
			}
			return true
		},
		/* 51 Action15 <- <{ p.setRelationTableNameReal(text) }> */
		func() bool {
			{
				add(ruleAction15, position)
			}
			return true
		},
		/* 52 Action16 <- <{ p.addComment(text) }> */
		func() bool {
			{
				add(ruleAction16, position)
			}
			return true
		},
		/* 53 Action17 <- <{p.setIndexName(text)}> */
		func() bool {
			{
				add(ruleAction17, position)
			}
			return true
		},
		/* 54 Action18 <- <{p.setIndexColumn(text)}> */
		func() bool {
			{
				add(ruleAction18, position)
			}
			return true
		},
		/* 55 Action19 <- <{p.setIndexColumn(text)}> */
		func() bool {
			{
				add(ruleAction19, position)
			}
			return true
		},
		/* 56 Action20 <- <{ p.setUniqueIndex() }> */
		func() bool {
			{
				add(ruleAction20, position)
			}
			return true
		},
		/* 57 Action21 <- <{ p.addGroup(text) }> */
		func() bool {
			{
				add(ruleAction21, position)
			}
			return true
		},
		/* 58 Action22 <- <{ p.addGroup(text) }> */
		func() bool {
			{
				add(ruleAction22, position)
			}
			return true
		},
		/* 59 Action23 <- <{ p.markGroupsDecl() }> */
		func() bool {
			{
				add(ruleAction23, position)
			}
			return true
		},
	}
	p.rules = _rules
	return nil
}
