name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install build tools
        run: go install github.com/pointlander/peg@latest
      - name: Generate parser
        run: peg erdm.peg
      - name: Build
        run: go build ./...
